"use client";

import { useState, useRef } from "react";

import { createClient } from "@/utils/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { 
  Camera,  
  ChevronRight, 
  ChevronLeft, 
  Shirt, 
  CheckCircle2,
  Image as ImageIcon,
  Loader2,
  Share2,
  Download,
  RefreshCcw,
  AlertCircle
} from "lucide-react";

const GARMENTS = [
  "Full Sleeve Shirt",
  "Half Sleeve Shirt",
  "Kurta",
  "Pant (Formal)",
  "Pant (Casual)",
  "Salwar Suit",
  "Saree Blouse",
];

export default function NewTrialPage() {
  const supabase = createClient();
  
  const [currentStep, setCurrentStep] = useState(1);
  const [isGenerating, setIsGenerating] = useState(false);
  
  // State for Step 1
  const [fabricFile, setFabricFile] = useState<File | null>(null);
  const [fabricPreview, setFabricPreview] = useState<string | null>(null);
  
  // State for Step 2
  const [customerFile, setCustomerFile] = useState<File | null>(null);
  const [customerPreview, setCustomerPreview] = useState<string | null>(null);
  
  // State for Step 3
  const [garmentType, setGarmentType] = useState<string>("");
  const [instructions, setInstructions] = useState<string>("");
  
  // Generation States
  const [resultUrl, setResultUrl] = useState<string | null>(null);
  const [generateError, setGenerateError] = useState<string | null>(null);

  // Refs for file inputs
  const fabricInputRef = useRef<HTMLInputElement>(null);
  const customerInputRef = useRef<HTMLInputElement>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>, type: "fabric" | "customer") => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Validate size (10MB)
    if (file.size > 10 * 1024 * 1024) {
      alert("File is too large. Max size is 10MB.");
      return;
    }

    // Validate type
    if (!["image/jpeg", "image/png", "image/webp"].includes(file.type)) {
      alert("Invalid file type. Only JPG, PNG, and WEBP are supported.");
      return;
    }

    const previewUrl = URL.createObjectURL(file);
    if (type === "fabric") {
      setFabricFile(file);
      setFabricPreview(previewUrl);
    } else {
      setCustomerFile(file);
      setCustomerPreview(previewUrl);
    }
  };

  const uploadToSupabase = async (file: File, bucket: string) => {
    const fileExt = file.name.split('.').pop();
    const fileName = `${Math.random().toString(36).substring(2, 15)}_${Date.now()}.${fileExt}`;
    const filePath = `${fileName}`;

    const { error: uploadError } = await supabase.storage
      .from(bucket)
      .upload(filePath, file);

    if (uploadError) {
      throw uploadError;
    }

    const { data: publicUrlData } = supabase.storage
      .from(bucket)
      .getPublicUrl(filePath);

    return publicUrlData.publicUrl;
  };

  const handleGenerate = async () => {
    if (!fabricFile || !customerFile || !garmentType) return;
    
    try {
      setIsGenerating(true);

      // 1. Upload files
      const fabricUrl = await uploadToSupabase(fabricFile, "fabrics");
      const customerUrl = await uploadToSupabase(customerFile, "customers");

      // 2. Call API Stub
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          fabricUrl,
          customerUrl,
          garmentType,
          instructions,
        }),
      });

      const data = await response.json();
      
      if (!response.ok) throw new Error(data.error || "Generation failed");

      // Success
      setResultUrl(data.data.resultUrl);
      
    } catch (error: unknown) {
      const err = error as Error;
      console.error(err);
      setGenerateError(err.message || "There was an error generating the trial.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleReset = () => {
    setCurrentStep(1);
    setFabricFile(null);
    setFabricPreview(null);
    setCustomerFile(null);
    setCustomerPreview(null);
    setGarmentType("");
    setInstructions("");
    setResultUrl(null);
    setGenerateError(null);
  };

  const handleShare = () => {
    if (!resultUrl) return;
    const text = "Check out this virtual trial generated by FitLook! " + resultUrl;
    window.open(`whatsapp://send?text=${encodeURIComponent(text)}`, "_blank");
  };

  const handleDownload = () => {
    if (!resultUrl) return;
    const a = document.createElement("a");
    a.href = resultUrl;
    a.download = "fitlook-trial.jpg";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const renderUploadZone = (type: "fabric" | "customer") => {
    const isFabric = type === "fabric";
    const preview = isFabric ? fabricPreview : customerPreview;
    const fileInputRef = isFabric ? fabricInputRef : customerInputRef;

    return (
      <div className="mt-6">
        <input 
          type="file" 
          accept="image/jpeg,image/png,image/webp"
          className="hidden" 
          ref={fileInputRef}
          onChange={(e) => handleFileChange(e, type)}
        />
        
        {preview ? (
          <div className="relative rounded-xl border-2 border-primary overflow-hidden group">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img 
              src={preview} 
              alt={`${type} preview`} 
              className="w-full h-80 object-cover"
            />
            <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
              <Button variant="secondary" onClick={() => fileInputRef.current?.click()}>
                Change Image
              </Button>
            </div>
          </div>
        ) : (
          <button 
            type="button"
            onClick={() => fileInputRef.current?.click()}
            className="w-full h-80 rounded-xl border-2 border-dashed border-muted-foreground/30 hover:border-primary hover:bg-primary/5 transition-colors flex flex-col items-center justify-center text-center p-6"
          >
            <div className="h-16 w-16 rounded-full bg-muted flex items-center justify-center mb-4">
              {isFabric ? <ImageIcon className="h-8 w-8 text-muted-foreground" /> : <Camera className="h-8 w-8 text-muted-foreground" />}
            </div>
            <h3 className="text-lg font-semibold mb-1">
              Click to {isFabric ? "upload fabric photo" : "upload customer photo"}
            </h3>
            <p className="text-sm text-muted-foreground mb-4">
              or drag and drop here
            </p>
            <p className="text-xs text-muted-foreground">
              Accepts JPG, PNG, WEBP (Max 10MB)
            </p>
          </button>
        )}
      </div>
    );
  };

  return (
    <div className="max-w-3xl mx-auto space-y-8 pb-12">
      <div className="space-y-2">
        <h1 className="text-3xl font-bold tracking-tight text-foreground">New Virtual Trial</h1>
        <p className="text-muted-foreground">Follow the steps to generate a realistic AI fitting for your customer.</p>
      </div>

      {/* Stepper */}
      <div className="flex items-center justify-between relative">
        <div className="absolute left-0 top-1/2 -translate-y-1/2 w-full h-1 bg-muted -z-10"></div>
        <div 
          className="absolute left-0 top-1/2 -translate-y-1/2 h-1 bg-primary -z-10 transition-all duration-300"
          style={{ width: `${((currentStep - 1) / 3) * 100}%` }}
        ></div>
        
        {[1, 2, 3, 4].map((step) => (
          <div 
            key={step} 
            className={`flex items-center justify-center h-10 w-10 rounded-full border-2 bg-background font-semibold transition-colors ${
              step < currentStep ? "border-primary bg-primary text-primary-foreground" :
              step === currentStep ? "border-primary text-primary" :
              "border-muted text-muted-foreground"
            }`}
          >
            {step < currentStep ? <CheckCircle2 className="h-5 w-5" /> : step}
          </div>
        ))}
      </div>

      <div className="min-h-[400px]">
        {/* Step 1: Fabric */}
        {currentStep === 1 && (
          <div className="animate-in fade-in slide-in-from-right-4 duration-300">
            <h2 className="text-xl font-semibold">Step 1: Fabric Selection</h2>
            <p className="text-sm text-muted-foreground mt-1">Upload a clear photo of the unstitched fabric, flat lay or hanging.</p>
            {renderUploadZone("fabric")}
          </div>
        )}

        {/* Step 2: Customer */}
        {currentStep === 2 && (
          <div className="animate-in fade-in slide-in-from-right-4 duration-300">
            <h2 className="text-xl font-semibold">Step 2: Customer Photo</h2>
            <p className="text-sm text-muted-foreground mt-1">Stand the customer in front of a plain wall, full body visible.</p>
            {renderUploadZone("customer")}
          </div>
        )}

        {/* Step 3: Garment */}
        {currentStep === 3 && (
          <div className="animate-in fade-in slide-in-from-right-4 duration-300">
            <h2 className="text-xl font-semibold">Step 3: Garment Type</h2>
            <p className="text-sm text-muted-foreground mt-1">Select the garment style you want the AI to generate.</p>
            
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4 mt-6">
              {GARMENTS.map((garment) => (
                <button
                  key={garment}
                  onClick={() => setGarmentType(garment)}
                  className={`flex items-center gap-3 p-4 rounded-xl border-2 text-left transition-all ${
                    garmentType === garment 
                      ? "border-accent bg-accent/5 shadow-sm" 
                      : "border-border hover:border-primary/50"
                  }`}
                >
                  <Shirt className={`h-6 w-6 ${garmentType === garment ? "text-accent" : "text-muted-foreground"}`} />
                  <span className={`font-medium ${garmentType === garment ? "text-foreground" : "text-muted-foreground"}`}>
                    {garment}
                  </span>
                </button>
              ))}
            </div>

            <div className="mt-8 space-y-2">
              <Label htmlFor="instructions">Special instructions for tailor style (Optional)</Label>
              <Input 
                id="instructions" 
                placeholder="e.g. V-neck, 3/4 sleeves, ankle length..." 
                value={instructions}
                onChange={(e) => setInstructions(e.target.value)}
              />
            </div>
          </div>
        )}

        {/* Step 4: Confirm */}
        {currentStep === 4 && (
          <div className="animate-in fade-in slide-in-from-right-4 duration-300">
            {isGenerating ? (
              <div className="flex flex-col items-center justify-center py-20 space-y-8">
                <div className="relative h-24 w-24">
                  <div className="absolute inset-0 rounded-full border-4 border-muted"></div>
                  <div className="absolute inset-0 rounded-full border-4 border-primary border-t-transparent animate-spin"></div>
                  <Loader2 className="absolute inset-0 m-auto h-8 w-8 text-primary animate-pulse" />
                </div>
                <div className="space-y-2 text-center">
                  <h3 className="text-2xl font-bold">AI is stitching your look…</h3>
                  <p className="text-muted-foreground">This typically takes 20-40 seconds.</p>
                </div>
              </div>
            ) : generateError ? (
              <Card className="border-destructive bg-destructive/5 mt-8">
                <CardContent className="flex flex-col items-center justify-center p-12 text-center space-y-4">
                  <AlertCircle className="h-12 w-12 text-destructive" />
                  <h3 className="text-xl font-bold">Generation Failed</h3>
                  <p className="text-muted-foreground">{generateError}</p>
                  <Button onClick={() => setGenerateError(null)} variant="outline" className="mt-4">
                    <RefreshCcw className="mr-2 h-4 w-4" /> Try Again
                  </Button>
                </CardContent>
              </Card>
            ) : resultUrl ? (
              <div className="space-y-8 mt-4">
                <div className="rounded-xl overflow-hidden border-4 border-muted relative group bg-black/5">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={resultUrl} alt="AI Generated Trial" className="w-full h-auto max-h-[70vh] object-contain" />
                </div>
                
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  <Button onClick={handleShare} className="h-12 bg-[#25D366] text-white hover:bg-[#128C7E]">
                    <Share2 className="mr-2 h-5 w-5" />
                    Share on WhatsApp
                  </Button>
                  <Button onClick={handleDownload} variant="outline" className="h-12">
                    <Download className="mr-2 h-5 w-5" />
                    Download Image
                  </Button>
                  <Button onClick={handleReset} variant="secondary" className="h-12">
                    <RefreshCcw className="mr-2 h-5 w-5" />
                    Try Another Fabric
                  </Button>
                </div>
              </div>
            ) : (
              <>
                <h2 className="text-xl font-semibold">Step 4: Confirm & Generate</h2>
                <p className="text-sm text-muted-foreground mt-1">Review your selections before generating.</p>
                
                <Card className="mt-6 border-2 border-primary/20">
                  <CardContent className="p-6">
                    <div className="grid grid-cols-2 gap-6">
                      <div>
                        <Label className="text-muted-foreground mb-2 block">Fabric</Label>
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img src={fabricPreview!} alt="Fabric" className="w-full h-40 object-cover rounded-lg border" />
                      </div>
                      <div>
                        <Label className="text-muted-foreground mb-2 block">Customer</Label>
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img src={customerPreview!} alt="Customer" className="w-full h-40 object-cover rounded-lg border" />
                      </div>
                    </div>
                    
                    <div className="mt-6 pt-6 border-t flex justify-between items-center">
                      <div>
                        <Label className="text-muted-foreground block">Selected Garment</Label>
                        <p className="text-lg font-semibold">{garmentType}</p>
                      </div>
                      {instructions && (
                        <div className="text-right max-w-[50%]">
                          <Label className="text-muted-foreground block">Instructions</Label>
                          <p className="text-sm truncate" title={instructions}>{instructions}</p>
                        </div>
                      )}
                    </div>
                  </CardContent>
                </Card>

                <div className="mt-8 text-center">
                  <Button 
                    onClick={handleGenerate} 
                    className="w-full h-14 text-lg bg-accent text-accent-foreground hover:bg-accent/90"
                  >
                    Generate AI Trial
                  </Button>
                  <p className="text-xs text-muted-foreground mt-3">
                    Generation takes 20–40 seconds depending on server load.
                  </p>
                </div>
              </>
            )}
          </div>
        )}
      </div>

      {/* Navigation Buttons - Hide during generation or on success/error */}
      {currentStep < 5 && !isGenerating && !resultUrl && !generateError && (
        <div className="flex justify-between pt-6 border-t">
          <Button 
            variant="outline" 
            onClick={() => setCurrentStep(prev => Math.max(1, prev - 1))}
            disabled={currentStep === 1 || isGenerating}
          >
            <ChevronLeft className="mr-2 h-4 w-4" />
            Back
          </Button>
          
          {currentStep < 4 && (
            <Button 
              onClick={() => setCurrentStep(prev => Math.min(4, prev + 1))}
              disabled={
                (currentStep === 1 && !fabricFile) || 
                (currentStep === 2 && !customerFile) || 
                (currentStep === 3 && !garmentType)
              }
            >
              Next
              <ChevronRight className="ml-2 h-4 w-4" />
            </Button>
          )}
        </div>
      )}
    </div>
  );
}
